Update website
blz-it/blz-it.de pull request #256
Opened 2024-07-16 12:51 UTC by styrix560

2024-07-16 12:52 UTC, styrix560 commented
The images (and dates) for the timeline are still missing.

2024-07-20 11:58 UTC, JonasWanke requested changes

2024-07-20 11:58 UTC, JonasWanke commented on public/locales/de/translation.json
> +        "wsg": "Skill 08 bei den WorldSkills 2024 Lyon"
```suggestion
        "wsg": "Skill 08 bei den WorldSkills Lyon 2024"
```

2024-07-20 11:58 UTC, JonasWanke commented on public/locales/de/translation.json
> +          "title": "EuroSkills Competition 2023 Gdansk",
```suggestion
          "title": "EuroSkills Gdańsk 2023",
```

2024-07-20 11:58 UTC, JonasWanke commented on public/locales/de/translation.json
> +          "title": "WorldSkills Competition 2024 Lyon",
```suggestion
          "title": "WorldSkills Lyon 2024",
```

2024-07-20 11:58 UTC, JonasWanke commented on public/locales/de/translation.json
> +          "title": "WorldSkills Competition 2024 Lyon",
```suggestion
          "title": "WorldSkills Lyon 2024",
```

2024-07-20 11:58 UTC, JonasWanke commented on public/locales/en/translation.json
> +          "title": "WorldSkills Competition 2024 Lyon",
```suggestion
          "title": "WorldSkills Lyon 2024",
```

2024-07-20 11:58 UTC, JonasWanke commented on public/locales/en/translation.json
> +        "wsg": "Skill 09 at the WorldSkills 2024 Lyon"
```suggestion
        "wsg": "Skill 09 at the WorldSkills Lyon 2024"
```

2024-07-20 11:58 UTC, JonasWanke commented on public/locales/en/translation.json
> +          "title": "EuroSkills Competition 2023 Gdansk",
```suggestion
          "title": "EuroSkills Gdańsk 2023",
```

2024-07-20 11:58 UTC, JonasWanke commented on public/locales/en/translation.json
> +          "title": "WorldSkills Competition 2024 Lyon",
```suggestion
          "title": "WorldSkills Lyon 2024",
```

2024-07-20 16:08 UTC, JonasWanke approved these changes

2024-07-20 17:24 UTC, merged