Update Everything
blz-it/blz-it.de pull request #285
Opened 2024-10-12 18:47 UTC by Benjamin-Frost

Closes: #267

2024-10-13 09:02 UTC, JonasWanke requested changes

2024-10-13 09:02 UTC, JonasWanke commented on src/components/NoTranslate.astro
> +  availableLanguages: (keyof typeof languages)[];
```suggestion
  availableLanguages: Languages[];
```

2024-10-13 09:02 UTC, JonasWanke commented on src/components/Header.astro
> +    name: "Full Stack",
```suggestion
    name: "Full-Stack",
```

2024-10-14 08:58 UTC, Benjamin-Frost commented on src/assets/skill-08.jpg
I can convert it if you want, but Astro automatically converts all images to WebP format with optimized resolution during the build process.

2024-10-14 09:02 UTC, Benjamin-Frost commented on src/middleware.ts
> +      new URL(`/${defaultLang}${ctx.url.pathname}`, ctx.url),
No, the `Astro` global is not available in the middleware.

2024-10-14 09:08 UTC, Benjamin-Frost commented on .github/dependabot.yml
Yes, this is intentional. Updating every dependency to its latest version doesn’t provide significant benefits, especially since the final output is just an HTML website. Additionally, some packages don’t follow semantic versioning, which could lead to breaking changes being introduced unintentionally.

If we wanted the latest versions during the build process, we could use `yarn install`, but we intentionally use the `--frozen-lockfile` option. This ensures the project builds with the exact versions we know work. As for security concerns, Dependabot still creates pull requests if any vulnerabilities are detected.

2024-10-14 17:09 UTC, JonasWanke approved these changes

2024-10-14 17:10 UTC, merged